from .auth_routes import auth
from .users_routes import users
from .courses_routes import courses
from .crystals_routes import crystal
from .lightsabers_routes import lightsaber
from .master_routes import masters
from .padawan_courses_routes import padawan_course
from .padawans_routes import padawans
from .species_routes import species
from .temples_routes import temples