from .auth_controllers import *
from .users_controllers import *
from .courses_controllers import *
from .crystals_controllers import *
from .lightsabers_controllers import *
from .master_controllers import *
from .padawan_courses_controllers import *
from .padawans_controllers import *
from .species_controllers import *
from .temples_controllers import *